name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ./build
      
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
    
    - name: publish
      run: docker push liop/hikyuu:${{ steps.previoustag.outputs.tag }}
